Project/Project/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('weather.urls'))
]

Project/weather/urls.py
from django.conf.urls import url

from . import views
app_name = 'weather'

urlpatterns = [
    url(r'^json/', views.index, name='index'),
    url(r'^$', views.first_page, name='first'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^login/',views.UserLogin, name='login'),
    url(r'^register/',views.register, name='register'),
    url(r'^logout/',views.UserLogout, name='logout'),
    url(r'^map/',views.map, name='map'),
    url(r'^dash/(?P<pid1>[0-9]+)/', views.detail, name='detail'),
    url(r'^addplant/', views.addplant, name='addplant'),
    url(r'^numplants/',views.numplants,name='numplants')
]

Project/weather/models.py
from django.db import models

# Create your models here.
class Weather(models.Model):
    temperature = models.CharField(max_length = 5)
    humidity = models.CharField(max_length = 5)
    check = models.CharField(max_length = 8)
    pub_date = models.DateTimeField('date published')

class plantid(models.Model):
    pid = models.IntegerField(primary_key = True)
    plant_name = models.CharField(max_length = 25,null=True)
    latitude = models.CharField(max_length = 10,null=True)
    longitude = models.CharField(max_length = 10,null=True)
    def __str__(self):
        return str(self.pid)

class Plant(models.Model):
    pid = models.ForeignKey(plantid,null=True)
    moisture = models.CharField(max_length = 8,null=True)

class Waterlevel(models.Model):
    #reading = models.CharField(max_length = 10)
    #bucket = models.CharField(max_length = 10)
    water_level = models.CharField(max_length = 10)


Project/weather/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	
	class Meta:
		model = User
		fields = ['username','email','password']

Project/weather/views.py
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render,redirect
from .models import Weather,Plant,Waterlevel,plantid
from django.utils import timezone
from django.core import serializers

from django.contrib.auth import authenticate,login,logout
from .forms import UserForm
from django.contrib.auth.decorators import login_required

def first_page(request):
    return render(request, "slide.html")

@csrf_exempt
def index(request):
    if request.method == 'POST':
        data1 = request.POST['data'].split(', ')
        if int(data1[2]) > 100:
                data1[2] = 'raining'
        else:
                data1[2] = 'no rain'
        for n  in range(1,len(data1) - 3):
            mois = Plant.objects.create(pid = plantid.objects.get(pid = n),moisture = data1[n+3])
            mois.save()
        temp = Weather.objects.create(temperature = data1[0],humidity = data1[1],pub_date = str(timezone.now()),check = data1[2])
        level = Waterlevel.objects.create(water_level = data1[3])
        temp.save()
        level.save()
        return HttpResponse(timezone.now())
    else:
        return HttpResponse(timezone.now())

def detail(request,pid1):
    if not request.user.is_authenticated():
        return redirect('weather:login')
    else:
        h = (list(filter(lambda x: x['fields'], json.loads(serializers.serialize('json',Plant.objects.filter(pid=pid1)))))[::-1])
        h1 = (list(filter(lambda x: x['fields'], json.loads(serializers.serialize('json',plantid.objects.filter(pid=pid1)))))[::-1])
        weather = Weather.objects.get(pk = Weather.objects.count())
        if len(h) == 0:
            return render(request, "Plants.html",{'moisture':"None",'latitude':h1[0]['fields']['latitude'],'longitude':h1[0]['fields']['longitude'],'name':h1[0]['fields']['plant_name'],'pid':pid1,'weather':weather})
        #return JsonResponse({"loc":html, "values":html1}, safe=False)
        return render(request, "Plants.html",{'moisture':h[0]['fields']['moisture'],'latitude':h1[0]['fields']['latitude'],'longitude':h1[0]['fields']['longitude'],'name':h1[0]['fields']['plant_name'],'name':h1[0]['fields']['plant_name'],'pid':pid1,'weather':weather})

def dashboard(request):
    if not request.user.is_authenticated():
        return redirect('weather:login')
    else:
        if request.method == 'GET':
            weather = Weather.objects.get(pk = Weather.objects.count())
            level = Waterlevel.objects.get(pk = Waterlevel.objects.count())
            json_temp = [Weather.objects.get(pk= Weather.objects.count() - k).temperature for k in range(0,11)][::-1]
            json_humid = [Weather.objects.get(pk= Weather.objects.count() - k).humidity for k in range(0,11)][::-1]
            return render(request, "graph.html", {'weather':weather,'plantid':plantid,'level':level,'json_temp':json_temp,'json_humid':json_humid})

@csrf_exempt
def addplant(request):
    if not request.user.is_authenticated():
        return redirect('weather:login')
    else:
        if request.method == "POST":
            plant_name = request.POST['a1']
            latitude = request.POST['a2']
            longitude = request.POST['a3']
            p = plantid.objects.count()
            plant = plantid.objects.create(pid = p+1,plant_name = plant_name,latitude = latitude,longitude = longitude)
            plant.save()
            return redirect('weather:dashboard')
            #print(plant_name)
        return render(request, 'add_plant.html')

def map(request):
    if not request.user.is_authenticated():
        return redirect('weather:login')
    else:
        if request.method == 'GET':
            weather = Weather.objects.get(pk = Weather.objects.count())
            p = plantid.objects.all()
            mois = []
            plant = []
            for i in p:
                m = list(filter(lambda x: x['fields'], json.loads(serializers.serialize('json',plantid.objects.filter(pid = i.pid)))))[::-1]
                for j in m:
                    plant.append(float(j['fields']['latitude']))
                    plant.append(float(j['fields']['longitude']))
                l = list(filter(lambda x: x['fields'], json.loads(serializers.serialize('json',Plant.objects.filter(pid = i.pid)))))[::-1]
                if len(l) != 0:
                	mois.append(l[0]['fields']['moisture'])
                else:
                    mois.append('None')
            level = Waterlevel.objects.get(pk = Waterlevel.objects.count())
            #print(weather.pub_date)
            #return JsonResponse({'plant':plant,'mois':mois},safe=False)
            return render(request, "map.html", {'weather':weather,'level':level,'mois':mois,'plant':plant})

@csrf_exempt
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
    	user = form.save(commit=False)
    	username = form.cleaned_data['username']
    	password = form.cleaned_data['password']
    	user.set_password(password)
    	user.save()
    	user = authenticate(username = username, password = password)
    	if user is not None:
    		if user.is_active:
    			login(request,user)
    			return redirect('weather:dashboard')
    return render(request,'register.html')

@csrf_exempt
def UserLogin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('weather:dashboard')
            else:
                return render(request,'login.html',{'context': 'This user is already logged in.'})
        else:
            return render(request,'login.html',{'context': 'Either Username or Password are wrong.'})
    return render(request,'login.html')
    

def UserLogout(request):
	logout(request)
	return redirect('weather:login')
	

def numplants(request):
    plant = plantid.objects.all()
    arr = []
    for  p in plant:
        arr.append(p.pid)
    return JsonResponse({'pid':arr},safe=False)

Project/weather/templates/Plants.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>PLANT-{{pid}} INFO</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.min.css' %}"rel="stylesheet">
	<link href="{% static 'css/datepicker3.css'%}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="{% static 'css/rain.css' %}">
	<link href="{% static 'css/font-styles/Montserrat.css' %}" rel="stylesheet">
	<script src="{% static 'js/RGraph.common.core.js' %}" ></script>
	<script src="{% static 'js/RGraph.meter.js' %}" ></script>
	<script src="{% static 'js/vendor/modernizr-2.6.2.min.js' %}"></script>
	<script>
    	fetch('/numplants/').then(res => res.json()).then(id => {
    		let list = id.pid.map(d => `<a class="dropdown-item" href='/dash/${d}' style="color:black;font-size:20px;text-decoration:none;">Plant ${d}<hr></a>`).join('')
    		document.querySelector('#getbutton').innerHTML = `
    			${list}
    			<a class="dropdown-item" href="{% url 'weather:addplant' %}" style="color:black;font-size:20px;text-decoration:none;">ADD PLANT&emsp;<em class="fa fa-plus"></em></a>
    		`
    	})
    	</script>
</head>
<body>
	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">

			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand"><span>Plant</span>Monitoring</a>
				<div class = "btn-group pull-right">
				<button class="navbar-brand pull-right btn btn-primary dropdown-toggle" align="center" type="button" data-toggle="dropdown">
				<em class="fa fa-info"></em> Plant info
				</button>
				<div class="dropdown-menu" id="getbutton">
					
				</div>
				</div>
			 </div>
	</nav>
	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<div class="profile-sidebar">
			<div class="profile-userpic">
				<img src="{% static 'images/plant.png' %}" class="img-responsive" alt="">
			</div>
			<div class="profile-usertitle" style="padding-top:10px;">
				{% if user.is_authenticated %}
					<div class="profile-usertitle-name">{{ request.user.username }}</div>
				{% else %}
					<div class="profile-usertitle-name">Not Loggedin</div>
				{% endif %}
			</div>
			<div class="clear"></div>
		</div>
		<div class="divider"></div>
		<ul class="nav menu">
			<li><a href="{% url 'weather:dashboard' %}"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a></li>
			<li><a href="{% url 'weather:map' %}"><em class="fa fa-map">&nbsp;</em> Map</a></li>
			<li><a href="{% url 'weather:logout' %}"><em class="fa fa-power-off" >&nbsp;</em> Logout</a></li>
		</ul>
		<hr>
		<div class = "rain1">
			<p style="font-size:25px;color:black">Weather Condition:</p>
			{% if weather.check == "no rain" %}
			<div class="icon sunny">
			  	<div class="sun">
			  	  <div class="rays"></div>
			  	</div>
			</div>
			{% else %}
		
			<div class="icon rainy">
				<div class="cloud"></div>
		  		<div class="rain"></div>
			</div>
			{% endif %}
		</div>

	</div>
	<!--div id="demo-content">
		<div id="loader-wrapper">
			<div id="loader"></div>
			<div class="loader-section section-left"></div>
            		<div class="loader-section section-right"></div>
		</div>
	</div-->
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#">
					<em class="fa fa-info" style="color:blue"></em>
				</a></li>
				<li class="active">Plant info</li>
			</ol>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">PLANT - {{pid}}</h1>
			</div>
		</div>
		<form class="form-horizontal">
			<div class="form-group">
					<label class="col-sm-2 control-label" style="font-size:20px">PLANT NAME:-</label>
				<div class="col-sm-5">
					<input class="form-control" id="Mois" type="text" value="{{name}}">
				</div>
			</div>
		</form>
		{% if moisture == "None" %}
			<div style="color:red;font-size:35px;text-align:center">This plant is not been monitered!!!</div><br>
		{% endif %}
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default chat">
					<div class="panel-heading">
							<b>SOIL MOISTURE</b><span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span>
					</div>
					<div class="panel-body">
						<form class="form-horizontal">
							<div class="form-group">
							  <div class="col-sm-15">
								<input class="form-control" id="Mois" type="text" value="{{moisture}}">
							  </div>
							</div>
						</form>
			     		</div>
			     		{% if moisture != "None" %}
					<center><canvas id="cvs" width="600" height="300">[No canvas support]</canvas></center>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="panel-heading"><b>PLANT IS LOCATED AT</b></div>
			<div class="col-md-6">
				<div class="panel panel-default chat">
					<div class="panel-heading">
							<b>LATITUDE</b><span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span>
					</div>
					<div class="panel-body">
						<form class="form-horizontal">
							<div class="form-group">
							  <div class="col-sm-15">
								<input class="form-control" id="Mois" type="text" value="{{latitude}}">
							  </div>
							</div>
						</form>
			     		</div>
				</div>
			
			</div>
			<div class="col-md-6">
				<div class="panel panel-default chat">
					<div class="panel-heading">
							<b>LONGITUDE</b><span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span>
					</div>
					<div class="panel-body">
						<form class="form-horizontal">
							<div class="form-group">
							  <!--label class="col-sm-2 control-label">Temp:-</label-->
							  <div class="col-sm-15">
								<input class="form-control" id="Mois" type="text" value="{{longitude}}">
							  </div>
							</div>
						</form>
			     		</div>
				</div>
			
			</div>
		</div>
	</div>
	
	<script>
		function changediv()
		{
			document.getElementById("actuator").innerHTML = document.getElementById("actuator").innerHTML == "OFF{{pid}}" ?  "ON{{pid}}" : "OFF{{pid}}"
		}
        	var meter = new RGraph.Meter({
            		id: 'cvs',
            		min: 0,
            		max: 100,
            		value: {{moisture}},
            		options: {
                		greenColor: 'Gradient(green:#040)',
                		yellowColor: 'Gradient(#ff0:#440)',
                		redColor: 'Gradient(#f00:#400)',
                		valueText: true,
                		valueTextUnitsPost: {{moisture}} < 41.3 ? '\ndying':'\nalive',
                		textAccessible: false
            		}
        	}).draw();
    	</script>
	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

Project/weather/templates/add_plant.html
{% load staticfiles %}
<html>
<body>
<style>
.previous {
    background-color: #f1f1f1;
    color: black;
    font-size:28px;
}
.defaultTextBox {
    padding: 0;
    height: 30px;
    position: relative;
    left: 0;
    outline: none;
    border: 2px solid #cdcdcd;
    border-color: rgba(0,3,0,2.15);
    background-color: white;
    font-size: 16px;
}
.advancedSearchTextbox {
    width: 152px;
    margin-right: -4px;
}
.button {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s;
    transition-duration: 0.4s;
}
.button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
.buttone {
  display: inline-block;
  padding: 15px 25px;
  font-size: 24px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #4CAF50;
  border: none;
  border-radius: 15px;
  box-shadow: 0 9px #999;
}

.buttone:hover {background-color: #3e8e41}

.buttone:active {
  background-color: #3e8e41;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}
p {
  color: white;
  font-size: 30px;
}
</style>
<body background="{% static 'images/addplant.jpg' %}">
	<button class="button button2" onclick="window.open('{% url 'weather:dashboard' %}', '_self')">&laquo; Go  back</button>

	<center>
	<br><br><br><br><br><br><br><br>
	<form method="POST">
		<p>PLANT NAME:</p>
		<input type="text" class="defaultTextBox advancedSearchTextBox" name="a1" required><br>
		<p>LATITUDE:</p>
		<input type="text" class="defaultTextBox advancedSearchTextBox" name="a2" required><br>
		<p>LONGITUDE:</p>
		<input type="text" class="defaultTextBox advancedSearchTextBox" name="a3" required><br>
		<br><br>
		<button class="buttone" typr="submit">Submit</button>
	</form> 
	</center>
	</body>
</html>




Project/weather/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="{% static 'js/jquery_min.js' %}"></script>
  <script src="{%  static 'js/bootstrap.min.js' %}"></script>
  <link href="{% static 'css/font-awesome.min.css' %}"rel="stylesheet">
<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: green;
    color: white;
	//display:block;
	margin:10px;
	padding:14px;
    //padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    border-radius:10px;
}
button:hover {
    opacity: 0.8;
}

.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
	height:100px;
	width:100px;
	border-radius:100px;
	
}
label{
	color:white;
	font-size:18px;
}
.container {
    padding: 16px;
	opacity:1;
}

span.psw {
    float: right;
    padding-bottom: 16px; 
	
}
a{
	 text-decoration:none;
	 font-size:18px;
	 color:#66FF66;	
}
/* The Modal (background) */
.modal {
	
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    /*background-color: rgb(0,0,0); Fallback color 
    background-color: rgba(0,0,0,0.4);  Black  opacity */
    padding-top: 160px;	
}

/* Modal Content/Box */
.modal-content {
    padding: 50px;	
    background:rgba(0,0,0,0.5);
    margin: 0% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
	border-radius:20px;
    width: 25%; /* Could be more or less, depending on screen size */
}


.close:hover, .close:focus {
    color: red;
    cursor: pointer;
}

 /*Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}
input{
	border-radius:20px;
}
#background{
	background-attachment:fixed;
	background-repeat: no-repeat;
}
body{
	background-image: url("{% static '/images/Plant1.jpg' %}");	
	background-color:grey;
	height: 500px; 
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
	overflow: auto;
}
h2{
	color:white ;
	font-size:25px;
}
header {
    padding: 1em;
    color: white;
   background-color: #100000;
    background:rgb(0,0,3);
	clear: left;
    text-align: center;
}
.a:hover  {
    color:green;
    text-decoration:underline;
}
</style>

<body>

	<div id="id01" class="modal">
		
		<form class="modal-content animate" method="POST">
			<a href="{% url 'weather:first' %}"><em class="fa fa-home">&nbsp;</em> HOME</a>
			<div class="imgcontainer">
				<img src="{% static '/images/Plant2.JPG/'%}" alt="Avatar" class="avatar">
			</div>
			<div style = "color:red;font-size:1em;font-family: 'Lato', sans-serif;text-align:center">{{ context }}</div>
			<div class="container">
					
					<label><b>Username</b></label>
					<input type="text" placeholder="Enter Username" name="username" required>
	
					<label><b>Password</b></label>
					<input type="password" placeholder="Enter Password" name="password" required>
        
					<center><button type="submit" class = "login">Login</button><br>
					<b style="color:white">Don't have an account then <a href = "{% url 'weather:register' %}" class="a">Sign Up</a></b>
					</center>
				
			</div>
   
		</form>
		
	</div>
	<!--script>
		document.getElementById('#c').innerHTML = {{context}}
	</script-->

</body>
</html>

Project/weather/templates/logout.html
<html>
	<body>
		<p>Logged out successfully.</p>
	</body>
</html>

Project/weather/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="{% static 'js/jquery_min.js' %}"></script>
  <script src="{%  static 'js/bootstrap.min.js' %}"></script>
  <link href="{% static 'css/font-awesome.min.css' %}"rel="stylesheet">
<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: green;
    color: white;
	//display:block;
	margin:10px;
	padding:14px;
    //padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    border-radius:10px;
}
button:hover {
    opacity: 0.8;
}

.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
	height:100px;
	width:100px;
	border-radius:100px;
	
}
label{
	color:white;
	font-size:18px;
}
.container {
    padding: 16px;
	opacity:1;
}

span.psw {
    float: right;
    padding-bottom: 16px; 
	
}
a{
	 text-decoration:none;
	 font-size:18px;
	 color:#66FF66;	
}
/* The Modal (background) */
.modal {
	
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 90%; /* Full height */
   overflow: none; /* Enable scroll if needed */
    /*background-color: rgb(0,0,0); Fallback color 
    background-color: rgba(0,0,0,0.4);  Black  opacity */
    padding-top: 50px;	
    padding-bottom: 100px;
}

/* Modal Content/Box */
.modal-content {
	padding: 50px;	
	background:rgba(0,0,0,0.5);
    margin: 0% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
	border-radius:20px;
    width: 25%; /* Could be more or less, depending on screen size */
}


.close:hover, .close:focus {
    color: red;
    cursor: pointer;
}

 /*Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}
input{
	border-radius:20px;
}
#background{
	background-attachment:fixed;
	background-repeat: no-repeat;
}
body{
	background-image: url("{% static '/images/Plant1.jpg/' %}");
	background-color:grey;
	height: 500px; 
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
	overflow: auto;
}
h3{
	color:white ;
	font-size:20px;
}
header {
    padding: 1em;
    color: white;
    background-color: #100000;
    background:rgb(0,0,3);
	clear: left;
    text-align: center;
}
.a:hover  {
    color:green;
    text-decoration:underline;
}
</style>

<body >
	
	<div id="id01" class="modal">
		<form class="modal-content animate" method = "POST">
		<a href="{% url 'weather:first' %}"><em class="fa fa-home">&nbsp;</em> HOME</a>
			<div class="imgcontainer">
				<img src="{% static '/images/Plant2.JPG/'%}" alt="Avatar" class="avatar">
			</div>
	
			<h3>CREATE NEW ACCOUNT</h3>
					<!--table>
						<!tr>
							<td>
								<label><b>FIRST NAME</b></label>
								<input type="text" placeholder="Enter Firstname" name="fname" required>
									
							</td>
							<td>
								<label><b>SURNAME</b></label>
								<input type="text" placeholder="Enter surname" name="sname" required>
							</td>
						</tr>
					</table-->
							
							<label><b>USER NAME</b></label>
							<input type="text" placeholder="Enter username" name="username" required>

							<label><b>EMAIL</b></label>
							<input type="text" placeholder="Enter Email" name="email" required>
			
							<label><b>PASSWORD</b></label>	
							<input type="password" placeholder="Enter Password" name="password" required>
							<center><button type="submit">Sign Up</button><br> 
							<b style="color:white">
							Already have an account then <a href="{% url 'weather:login' %}" class="a">Sign In</b></center>
		</form>
		</div>
	

</body>
</html>